# Generated by Django 2.1.7 on 2019-02-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190215_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='escolaridade',
            field=models.CharField(choices=[('EM', 'Ensino Médio'), ('NT', 'Nível Técnico'), ('NS', 'Nível Superior')], default='EM', max_length=2, verbose_name='Escolaridade'),
            preserve_default=False,
        ),
    ]
